### PR TITLE
Pkgconfig

### PR DESCRIPTION
**Pull request by phodina**
Hi,
thanks for an amazing library and LiveCaptions!

This adds the following:
- package version in CMakeLists.txt (better to have some releases and not just grab commits)
- template for pkg-config file (so it can be used as dependency)
- installation target for pkg-config.

I'd like to see LiveCaptions running on Alpine Linux on my "old" phone OnePlus 6 running [PostmarketOS](https://postmarketos.org/).

### CODE REVIEW

**Comment by phodina** [comment]
I'll try to push one more PR for CMake install targets since the files have to be manually installed in the APKBUILD. Also other package managers will benefit from calling just `DESTDIR="$pkgdir" cmake --install build`

**Comment by nekowinston** [comment]
It might be worth noting that #9 does some of the same things.

**Comment by phodina** [comment]
Thanks, yeah looks like it does the same mostly + Nix stuff

**Comment by abb128** [comment]
I went ahead and merged the nix flake PR, is any of this still needed?

**Comment by phodina** [comment]
@abb128  Most of stuff is already [there](https://github.com/abb128/april-asr/commit/b3708aa95c25f2cb3b3e76e74834ce70848296f9).

The only major missing this is the versioning to keep compatibility through SONAME. Here's how to set the  CMAKE [variable](https://github.com/abb128/april-asr/pull/13).

**Pull request closed without merging**
